name: neon
description: A Flutter plugin that allows you to use beautiful neon signs in your app.
version: 0.1.0
homepage: https://github.com/g0rdan/neon

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  async: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Monoton
      fonts:
        - asset: lib/fonts/Monoton/Monoton-Regular.ttf
    - family: Automania
      fonts:
        - asset: lib/fonts/Automania/Automania.ttf
    - family: Beon
      fonts:
        - asset: lib/fonts/Beon/Beon.otf
    - family: LasEnter
      fonts:
        - asset: lib/fonts/LasEnter/LasEnter.ttf
    - family: TextMeOne
      fonts:
        - asset: lib/fonts/TextMeOne/TextMeOne-Regular.ttf
    - family: Night-Club-70s
      fonts:
        - asset: lib/fonts/Night-Club-70s/Night-Club-70s-Bold.ttf
        - asset: lib/fonts/Night-Club-70s/Night-Club-70s-Regular.ttf
    - family: Membra
      fonts:
        - asset: lib/fonts/Membra/Membra.ttf
    - family: Samarin
      fonts:
        - asset: lib/fonts/Samarin/Samarin.ttf
    - family: Cyberpunk
      fonts:
        - asset: lib/fonts/Cyberpunk/Cyberpunk.ttf

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
